### PR TITLE
fix initial value and update loop

### LINKED ISSUE #54: Initial filter values are undefined.
Some think is not working with the filter. If I log the values, it's a loop.

### PR DESCRIPTION
**Pull request by mmaelicke**
fixes #54

I will add a commented review to explain what went wrong

### CODE REVIEW

File: src/context/data.tsx [hunk 1]
```diff
@@ -83,36 +80,52 @@ export const DataProvider: React.FC<React.PropsWithChildren> = ({
...
   const { inventory } = useOffline();
 
+  // define the setFilterValues function
+  const setFilterValues = (newValues: FilterValues) => {
+    setCurrentFilterValues({
+      height: { ...newValues.height },
+      radius: { ...newValues.radius}
+    })
+  } 
+
```
Comment (mmaelicke) [inline src/context/data.tsx:97]: You need to wrap the state update handler function by a function, that will leave the context.

File: src/context/data.tsx [hunk 2]
```diff
@@ -83,36 +80,52 @@ export const DataProvider: React.FC<React.PropsWithChildren> = ({
...
-        },
+        data: {...currentStats},
       });
 
+      // set the filter to the current min/max as the dataset changed
+      setCurrentFilterValues({
+        radius: {lower: currentStats.radiusMin, upper: currentStats.radiusMax},
+        height: {lower: currentStats.heightMin, upper: currentStats.heightMax}
+      })
+
```
Comment (mmaelicke) [inline src/context/data.tsx:128]: slight refactoring to be able to use the newly created min and max values also for the current filter. This means, whenever the underlying dataset is updated, the filter will also be reseted, what makes a lot of sense as filter values might otherwise lie outside of the new value ranges.

File: src/context/data.tsx [hunk 3]
```diff
@@ -181,8 +149,8 @@ export const DataProvider: React.FC<React.PropsWithChildren> = ({
           ...cloneDeep(
             allInventory.features.filter(
               (f) =>
-                f.properties.radius > filterValues.radius.lower / 100 &&
-                f.properties.radius < filterValues.radius.upper / 100 &&
```
Comment (mmaelicke) [inline src/context/data.tsx:185]: The conversion now happens only for visual reasons, directly in the range slider component

**Review by mmaelicke — COMMENTED** [review]
These are my comments, how I tried to fix the filter. From what I can tell it seems to work fine now. Not sure if this the 100% the best implementation.

File: src/context/data.tsx [hunk 4]
```diff
@@ -83,36 +80,52 @@ export const DataProvider: React.FC<React.PropsWithChildren> = ({
 
   // create state for synchronization
   const [synced, setSynced] = useState<boolean>(false);
+
   //TODO: Use real values instread.
-  const [filterValues, setFilterValues] = useState<FilterValues>({
-    radius: { lower: 4, upper: 50 },
-    height: { lower: 3, upper: 43 },
-  });
+  const [filterValues, setCurrentFilterValues] = useState<FilterValues | undefined>(undefined);
```
[the remark this answers is not in the document]
Comment (JesJehle) [reply src/context/data.tsx:85]: Ok, this is new to me, but makes sense. Thanks for clarification!

**Comment by JesJehle** [comment]
Thank you so much for the detailed explanations. I am learning a lot :)
